### ISSUE TITLE
HTTP-Version related Exception when connecting to a gRPC service hosted behind proxy (envoy / Ambassador)

### ISSUE THREAD

**Issue by SebastianGau** [grpc/grpc-dotnet#1287]
**Describe the bug**
Hello Everybody! I am trying to host a C#-based gRPC Server behind Ambassador. So this issue could potentially be related to Ambassador/envoy but also to the C# gRPC client libraries, so take this with a grain of salt... When following the [tutorial]( https://www.getambassador.io/docs/edge-stack/latest/howtos/grpc/) everything works fine up to the point where I try to implement TLS termination in Ambassador (but communication between ambassador and the grpc service is unencrypted). I.e. when trying to connect via a channel created by

```csharp
_channel = GrpcChannel.ForAddress("http://my.host.com:80");
```

everything works fine. As soon as I try to establish a channel via

```csharp
_channel = GrpcChannel.ForAddress("https://my.host.com:443"); // omitting the port does not change anything
```

and do any call the following exception is thrown:

```
Grpc.Core.RpcException: 'Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while server offers only version fallback.", DebugException="System.Net.Http.HttpRequestException: Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while server offers only version fallback.
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")'
```

The C# server within the pod is listening on port 5000 with http/2 without tls:

```csharp
public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.ConfigureKestrel(options =>
                    {
                        // Setup a HTTP/2 endpoint without TLS.
                        options.ListenAnyIP(5000,
                            options =>
                            {
                                options.Protocols = HttpProtocols.Http2;

                            });
                    });
                    webBuilder.UseStartup<Startup>();
                });
```

Deployment yaml:

```yaml
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: example-host
spec:
  hostname: my.host.com
  acmeProvider:
    authority: https://acme-v02.api.letsencrypt.org/directory # Optional: The CA you want to get your certificate from. Defaults to Let's Encrypt
    email: my@email.com
  requestPolicy:
    insecure:
      action: Route
---
apiVersion: getambassador.io/v2
kind: TLSContext
metadata:
  name: tls
spec:
  secret: my.host.com # this secret exists in the k8s default namespace, tls works perfectly (tested for webapps)
  hosts: 
  - "*"
  alpn_protocols: [ "h2, http/1.1" ] # i tried to add http/1.1 but this did not have any effect
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: grpc-dotnet
spec:
  grpc: true
  prefix: /greet.MyGreeterService/
  rewrite: /greet.MyGreeterService/
  service: grpcservice
  # allow_upgrade: # i also tried this
  # - h2
  # host: my.host.com # i also tried this
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: grpcservice
  name: grpcservice
spec:
  type: ClusterIP
  ports:
  - name: grpc-greet
    port: 80
    targetPort: grpc-api
  selector:
    service: grpcservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpcservice
spec:
  replicas: 1
  selector:
    matchLabels:
      service: grpcservice
  template:
    metadata:
      labels:
        service: grpcservice
    spec:
      containers:
      - name: grpcservice
        image: my.container.registry/grpcservice:latest
        ports:
        - name: grpc-api
          containerPort: 5000
      restartPolicy: Always
      imagePullSecrets:
      - name: mysecret
```

I also checked that the right alpn settings are applied in envoy.

**To Reproduce**
1. Follow the tutorial on https://www.getambassador.io/docs/edge-stack/latest/howtos/grpc/ , but use a C#-based gRPC Server
2. Add a TLS context based on an existing secret according to the tutorial
3. Try to connect via a C# gRPC Client via a secure channel

**Expected behavior**
The C# gRPC client should connect without any problems when establishing a secure channel. I assume it has something to do with http/2 and http/1.1. It could also be related to bugs in the C# grpc client libraries, thats why I am posting here. I really hope somebody has an idea about the root cause since I really tried everything and run out of ideas...

**Versions (please complete the following information):**
 - Abassador version 1.13.3
 - Kubernetes environment: Azure Kubernetes Service
 - Kubernetes Version 1.18.14
 - Grpc.AspNetCore nuget package version 2.37.0 on gRPC server and client
